#!/command/with-contenv sh

read cstart hstart range < /proc/self/uid_map 2>/dev/null
if [ "$hstart" != "0" ]
then
    echo "Starting: ROOTLESS..."
    mythbackend
else
    echo "Starting: ROOTFUL!!!"
    mythbackend --user mythtv
fi
